### ISSUE TITLE
dark 版本部分界面顶部没有覆盖

### ISSUE THREAD

**Issue by h0cheung** [vinceliuice/Orchis-kde#1]
![image](https://user-images.githubusercontent.com/36502569/101991751-952e2880-3ca6-11eb-8cf6-5b15a567a241.png)
![image](https://user-images.githubusercontent.com/36502569/101991771-bee74f80-3ca6-11eb-84aa-d39c4510409c.png)

**Comment by vinceliuice** [comment]
注销还这样吗？

**Comment by vinceliuice** [comment]
我也遇到了这个问题，重新设置一下color scheme主题就又好了，不知道是什么鬼

**Comment by vinceliuice** [comment]
感觉是kvantum或者kde设置软件的问题，因为我测试了所有的主题都有这个问题，重新设置color scheme主题就好了
