### ISSUE TITLE
which dock does this theme use?

### ISSUE THREAD

**Issue by suiahae** [vinceliuice/Orchis-kde#10]
which dock does this theme use?

![图片](https://user-images.githubusercontent.com/45323123/127656944-d28f2135-e30c-49c6-a0d7-c5a46b3fb576.png)

I have selected "Use desktop layout from theme".

![图片](https://user-images.githubusercontent.com/45323123/127657231-51162583-3c12-4f86-bd8d-d8909c2e8cbd.png)

But the dock is not displayed.

![图片](https://user-images.githubusercontent.com/45323123/127657524-bc39f151-1182-4da7-a584-e619362ff8b3.png)

Do I need additional dock software?

**Comment by vinceliuice** [comment]
`latte` You need install it

**Comment by suiahae** [comment]
> 
> 
> `latte` You need install it

thank you for your reply
