### ISSUE TITLE
Missing icons for input state

### ISSUE THREAD

**Issue by prettyv** [vinceliuice/Orchis-kde#15]
Compared to the official Breeze theme's `input.svg`, a few of the icons are missing here. Namely the following ids:
- input-num-on
- input-keyboard-virtual-on
- input-keyboard-virtual-off

And a few size variants as well, although some or all of these might be intentionally left out, not sure:
- 22-22-input-mouse-battery
- 16-16-input-mouse-battery
- 22-22-input-keyboard-virtual-on
- 22-22-input-keyboard-virtual-off
- 22-22-input-caps-off
- 22-22-input-num-on

I noticed mainly because I configured the keyboard `Lock Keys Status` applet to only show the numlock status, which currently produces an empty space in the tray without the corresponding icon.

![Screenshot_20220210_105910](https://user-images.githubusercontent.com/1702205/153383493-1908b02b-422b-4d98-b9bb-23d7893a4596.png)

**Comment by prettyv** [comment]
Thanks for adding the size variants, but the/my main issue was the missing `input-num-on` icon, basically a version of `input-caps-on` with a "1" instead of an "A". Would be nice if this could be added as well!

**Comment by vinceliuice** [comment]
Updated

**Comment by prettyv** [comment]
Great, thanks!
