### ISSUE TITLE
Wrong contrast for some icons

### ISSUE THREAD

**Issue by prettyv** [vinceliuice/Orchis-kde#16]
Since commit e8868720b70092260107838712740bef1f66cc3c there are some icons that now have wrong (I guess fill) colors:

![Screenshot_20220216_110200](https://user-images.githubusercontent.com/1702205/154241255-e83155e8-2485-40bf-a71e-acab6bb12ad9.png)

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
Fixed!

**Comment by prettyv** [comment]
Looking good, thanks!

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by prettyv** [comment]
@vinceliuice I found another issue of the same kind, this time it's the active state of the bluetooth indicator. More precisely icons `22-22-preferences-system-bluetooth-activated` and `16-16-preferences-system-bluetooth-activated` are missing the `ColorScheme-Text` class. I'd submit a PR, but I don't really have a proper SVG workflow besides editing the XML representation directly, so I thought I'd rather write first. If that would be generally sufficient for you I'll see if I can do that in the future.

![Screenshot_20220408_202026](https://user-images.githubusercontent.com/1702205/162499402-0f238152-3b8d-4cfd-bb79-1c4884891eb5.png)
