### ISSUE TITLE
A solid (opaque) version?

### ISSUE THREAD

**Issue by LeKruistz** [vinceliuice/Orchis-kde#17]
Can you please add a option for a kvantum and plasma theme but solid? because this kde version is transparent which is meant for using with blur but it looks out of place because gnome (gtk) version has the soild option while this kde (qt) version didn't have this option

**Comment by vinceliuice** [comment]
No problem!

**Comment by rekaerst** [comment]
@Kacper-Kondracki 
You can work around this by change the attribute `opacity` of `window-normal` and `window-normal-inactive` to `1`.

e.g. 
[Orchis-dark.svg:982](https://github.com/vinceliuice/Orchis-kde/blob/bd73f140fafb177ff6da32181064637596331688/Kvantum/Orchis-dark/Orchis-dark.svg?short_path=8f76726#L982)
```xml
 <path id="window-normal" d="m380 814.26h30v30h-30z" fill="#212121" fill-rule="evenodd" opacity="1" style="paint-order:normal"/>
 <path id="window-normal-inactive" d="m412 814.26h30v30h-30z" fill="#1c1c1c" fill-rule="evenodd" opacity="1" style="paint-order:normal"/>
```

**Comment by Kodehawa** [comment]
> 

Any news on this?

**Comment by xendak** [comment]
honestly, only the menus you can't "remove" the opacity without kvantum manager.. so you can just change everything that has the color of "#0f0f0f" to have opacity 1 and you get a solid theme
