### ISSUE TITLE
Titlebar blur gone on Plasma 5.25

### ISSUE THREAD

**Issue by Dener-Silva** [vinceliuice/Orchis-kde#18]
Hello

So I updated to the newest KDE version and the titlebar blur stopped working.

![image](https://user-images.githubusercontent.com/19142280/174448341-0b961baa-72b0-4a78-b255-f432f6c8582f.png)

This happens because Plasma 5.25 needs a new "mask" element so it knows what region to apply the blur to. This article explains how to fix it: https://psifidotos.blogspot.com/2022/03/kornersfix.html

I modified the light theme in a fork to test it out and it works.
![image](https://user-images.githubusercontent.com/19142280/174450135-bb832878-cc6b-4bfb-a603-2980b327a9c3.png)

I'd like to note that in order to fix the korners bug, I had to remove all fill gradients from the "shadows" on the mask and replace them with `fill="none"`. Just setting opacity to 0 didn't work on my machine.

I wasn't able to add blur to the bottom of the windows, but I imagine that's a limitation on Aurorae in general.

**Comment by Dener-Silva** [comment]
Thanks!
I'll do it as soon as I get the time. I'll try to explain it better:

The mask is this guy here to the left:
![image](https://user-images.githubusercontent.com/19142280/175328767-e524ab2e-5a42-4fa7-b7bc-4953ccfde76b.png)

It is made of 9 elements, called `mask-topleft`, `mask-bottomright`, and so on. It's just a copy of the decoration, with the colors changed.
![image](https://user-images.githubusercontent.com/19142280/175329357-25634a40-6292-477a-b443-77088d388b5a.png)

It must be the same size of the decoration, including shadows:
![image](https://user-images.githubusercontent.com/19142280/175331177-4508bda0-cd09-426f-97f6-b5f9cc30b1b9.png)

Aurorae will use this new mask to apply the blur effect. The visible area (here in white) will be blurry. The invisible area will not be blurry.

**Comment by sheeepdev** [comment]
Thanks for the explanation! I've mostly got it to work via copying the Orchis mask layers to the Orchis-dark svg, I've just noticed this minor issue which I probably created cuz I copied from the light version
![image](https://user-images.githubusercontent.com/68562536/175341567-875e8394-2fc4-4496-b650-09f90b065078.png)

**Comment by Dener-Silva** [comment]
Don't be too hard on yourself buddy.
I did it on the dark version now.
![image](https://user-images.githubusercontent.com/19142280/175422185-744316b1-fc7b-4760-b142-beed37c6b3fc.png)
I'll try to do it on the other versions (Nvidia, x1.5) this weekend and then submit a merge request.

**Comment by sheeepdev** [comment]
![image](https://user-images.githubusercontent.com/68562536/175490743-ebbb4796-cd82-4f09-ad8c-345dbe31c1d8.png)

**Comment by Dener-Silva** [comment]
Hi Sheeep,
It looks like you're using the Orchis-dark_x1.5 decorations.
Please go to System **Settings > Appearance > Window Decorations**, select **Orchis-dark** (not Orchis-dark_x1.5) and then **Apply**.
If that doesn't fix the issue, then I'm not really sure what's going wrong.

Unrelated, but it looks like you're not using the Kvantum theme. If you'd like to have the Orchis buttons, tabs and stuff you can follow this tutorial: https://youtu.be/zfOe1Kfb4WE?t=648

**Comment by sheeepdev** [comment]
> Hi Sheeep, It looks like you're using the Orchis-dark_x1.5 decorations. Please go to System **Settings > Appearance > Window Decorations**, select **Orchis-dark** (not Orchis-dark_x1.5) and then **Apply**. If that doesn't fix the issue, then I'm not really sure what's going wrong.
> 
> Unrelated, but it looks like you're not using the Kvantum theme. If you'd like to have the Orchis buttons, tabs and stuff you can follow this tutorial: [youtu.be/zfOe1Kfb4WE?t=648](https://youtu.be/zfOe1Kfb4WE?t=648)

I have the kvantum theme applied and I **don't** use the x1.5 version, but rather the normal verson

**Comment by sheeepdev** [comment]
> Thanks for the explanation! I've mostly got it to work via copying the Orchis mask layers to the Orchis-dark svg, I've just noticed this minor issue which I probably created cuz I copied from the light version ![image](https://user-images.githubusercontent.com/68562536/175341567-875e8394-2fc4-4496-b650-09f90b065078.png)
> 
> Sorry for the bad picture, but the titlebar blur issue is under your username (blur is normal but when it comes to the left corner it suddenly doesn't work). This is me just being stupid and lazy but yeah

This was the closest thing I could get to blur working. If you want, I can send you that file

**Comment by Dener-Silva** [comment]
Thanks Vince!

**Comment by sheeepdev** [comment]
I'm glad Vince fixed it!

As for my problem, @Dener-Silva, I know what it is but don't know how to solve it.

Basically, the theme has "fake" rounded corners. I'm using [ShapeCorners](https://github.com/ZacharyTalis/ShapeCorners) for rounded corners, and that's why its bugging out.

Before all of these bugs on 5.25, @Willy-JL fixed the fake corners for me but since I need to implement the masks it doesn't work.

**Comment by happyeggchen** [comment]
Hey guys how you did that, i'm trying to patch my theme too but it's not working

![image](https://user-images.githubusercontent.com/38799701/190409233-32881e5f-496b-4543-b46b-b2a175f24e1c.png)
