### ISSUE TITLE
Weird curve black bar under windows

### ISSUE THREAD

**Issue by jackdaw213** [vinceliuice/Orchis-kde#21]
I'm using the latest Orchis-KDE straight out from git, here is my current setup:
- Operating System: Arch Linux
- KDE Plasma Version: 5.25.4
- KDE Frameworks Version: 5.96.0
- Qt Version: 5.15.5
- Kernel Version: 5.18.16-arch1-1 (64-bit)
- Graphics Platform: X11
- Processors: 16 × AMD Ryzen 7 4800H with Radeon Graphics
- Memory: 15.1 GiB of RAM
- Graphics Processor: AMD RENOIR
- System Version: 1.0

And the problem:
![image](https://user-images.githubusercontent.com/103126046/183058266-2e65d14b-2e5a-46a2-9db9-2c8f1388de86.png)
As you can see there is a black bar under the window which doesn't look good. Is this a bug or it's a design choice ? Is there any way to get rid of it and curve the black window border instead ? Or we could keep the curve bar but blur it instead of leaving it transparent ?

**Comment by celianvdb** [comment]
Hi, I have exactly the same issue. Did you found a fix ?

**Comment by celianvdb** [comment]
Ok, I don't have nvidia GPU but the "Orchis-dark_Nvidia" thme in windows decoration fixed the issue.

**Comment by jackdaw213** [comment]
I do have Nvidia GPU and switching to "Orchis-dark_Nvidia" fixed the issue, thank you for the solution
