### ISSUE TITLE
Orchis kvantum theme: showFoto toolbar and status bar broken

### ISSUE THREAD

**Issue by Sadi58** [vinceliuice/Orchis-kde#3]
Among all applications, I've noticed a problem only in [showFoto](https://apps.kde.org/en/showfoto): I see an all-black toolbar and statusbar. No problem with the thumbbar on the left and the right sidebar.
As far as I know, this app is closely associated with digiKam, but no problem there.
I don't know if this can fixed in the theme...

**Comment by vinceliuice** [comment]
Could you give me a screenshot?

**Comment by Sadi58** [comment]
Screenshot 1 with Thumbbar, Toolbar and Statusbar  enabled:
![Screenshot_2020-12-23-11-51-29](https://user-images.githubusercontent.com/6375934/102978607-d24fb180-4515-11eb-9ef1-63a5a4d5a3da.jpg)
Screenshot 2 with Toolbar and Statusbar disabled and enabled again:
![Screenshot_2020-12-23-11-52-13](https://user-images.githubusercontent.com/6375934/102978714-fe6b3280-4515-11eb-92e4-f126d2fd9f7c.jpg)
Screenshot 3 with KvantumArc theme:
![Screenshot_2020-12-23-12-00-01](https://user-images.githubusercontent.com/6375934/102979124-ab45af80-4516-11eb-8412-1167a2cb41d4.jpg)

**Comment by vinceliuice** [comment]
Does it still broken after reboot?

**Comment by Sadi58** [comment]
Yes. After reboot, I see the same as screenshot 1.

**Comment by vinceliuice** [comment]
![Screenshot_20201223_210130](https://user-images.githubusercontent.com/7604295/102998903-1321e780-4563-11eb-8336-0f82478a7026.jpg)

**Comment by vinceliuice** [comment]
I did not find this issue on my desktop

**Comment by Sadi58** [comment]
Interesting.
Could it be due to my system/app version?
Showfoto Version 6.4.0
Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2

**Comment by Sadi58** [comment]
Oooops. It appeared when I deleted its config file ~/.config/showfotorc
I'll try to spot what breaks...

**Comment by Sadi58** [comment]
I give up. I couldn't find what caused it.
My previous config file was 94.9 Kb and now, after making some custom settings, the new one is 12.6 Kb.
Sorry about this. I should have thought of this, and tried with a clean showFoto...
