### ISSUE TITLE
How to get the solid plasma theme

### ISSUE THREAD

**Issue by retroflexivity** [vinceliuice/Orchis-kde#31]
Hi,

It's probably a stupid question, but how do I set the solid plasma style (for widgets etc)? I can see it's there (https://github.com/vinceliuice/Orchis-kde/tree/main/plasma/desktoptheme/Orchis/solid), but only 'Orchis' shows up in plasma style settings.

**Comment by vinceliuice** [comment]
Open the panel `edit mode` set `opacity` to `opague`, the opague mode is solid mode

**Comment by retroflexivity** [comment]
Great, thank you!
