### ISSUE TITLE
SDDM6 Support

### ISSUE THREAD

**Issue by geser2008** [vinceliuice/Orchis-kde#33]
Hello!
Please add SDDM6 support for SDDM theme if possible.
The theme is not compatible with PLASMA 6.

![20240515_135524_2](https://github.com/vinceliuice/Orchis-kde/assets/1221343/7f995c88-1eb7-4487-939e-f4d1e9b663c4)

Thank you!

**Comment by vinceliuice** [comment]
It's already fixed https://github.com/vinceliuice/Orchis-kde/tree/main/sddm/6.0

**Comment by PetroZaburko** [comment]
![IMG_20240919_134518_edit_259940353662418](https://github.com/user-attachments/assets/e2a728ab-f61a-4cc6-9e44-a6ab76589fdb)
 In my case, problem looks like this. What can I do?

**Comment by PetroZaburko** [comment]
Yes, it works. Great. Thanks!
