### ISSUE TITLE
(SDDM) cannot assign to non-existent property "fontSize"

### ISSUE THREAD

**Issue by DaRandomCube** [vinceliuice/Orchis-kde#34]
system: fedora 41 beta
kde version: 6.2
![image](https://github.com/user-attachments/assets/b4710ba8-1304-4802-9363-8ce104984a78)
aand that's it

**Comment by PetroZaburko** [comment]
Any solution? Had the same problem after I updated my KDE Plasma from 6.15 to 6.20.
