### ISSUE TITLE
Window borders expand beyond what should be normal when using display scaling

### ISSUE THREAD

**Issue by jmc-figueira** [vinceliuice/Orchis-kde#6]
The window borders expand beyond what's expected when Display Scaling is set in the display settings (in my case, I have it set at 150%). It seems related to [this issue](https://www.reddit.com/r/kde/comments/fkygkj/when_i_change_the_global_display_scale_windows/).

Examples:
![orchis-bug1](https://user-images.githubusercontent.com/6634716/103476943-cf747c80-4db1-11eb-8ecb-eb4ffa8af397.png)
![orchis-bug2](https://user-images.githubusercontent.com/6634716/103476946-d3a09a00-4db1-11eb-8eac-e35e164ea89e.png)

Additionally, although this is not necessarily related to the above issue, is there an included theme for the latte dock? I seem to be unable to replicate the appearance of the dock in your screenshots (namely, the margin below it).

Thanks in advance.

**Comment by vinceliuice** [comment]
I added a x1.5 version for this scaling

**Comment by jmc-figueira** [comment]
Thank you!
