### ISSUE TITLE
Windows border is huge when using global scaling at 125%

### ISSUE THREAD

**Issue by darktaiga01** [vinceliuice/Orchis-kde#7]
Hi @vinceliuice,

Thanks for your awesome theme, I love it very much. But I've got a problem. When I set my display at 125%, the application is huge like below photo.
![image](https://user-images.githubusercontent.com/22326202/110912691-d1753180-8346-11eb-842d-43d2fca09c5d.png)
Is there any way to fix it. I've set at 100% and the border is fine, but it's hard to use 100% on my laptop's 15'6 screen.
Thanks for your attention. I’m looking forward to your reply.

**Comment by melianmiko** [comment]
++
I have some bug, fix please

**Comment by zbeeble49** [comment]
Have same issue with huge window borders and did some testing: 

seems to be problem with fractional scaling as it works with 100% scaling (way too small on a HiDPI screen) and 200% scaling (wastes a lot of space on a 13" or 14" notebook screen). Anything between, like my preferred 150% scaling, and the Window Decorations show a huge border.

As there seems to be no fix will use other dark theme instead.

**Comment by zbeeble49** [comment]
No have not seen there is a 1.5x version - which happens to be the scaling I am using for my desktop. Will use this instead of the "Layan" windows decorations (for everything else I have used Orchis-dark...)

**Comment by pdf** [comment]
It would be really nice if the theme could honor the `Window border size` setting in the `Window Decorations` kcm.

**Comment by jclsn** [comment]
+1

**Comment by jclsn** [comment]
@darktaiga01 The 1.5x version does not solve the issue. The Breeze theme and some others don't have this issue. So there is definitely a way to fix this. Maybe ask im the KDE visual design Telegram group

https://telegram.me/vdgmainroom

**Comment by Gpinchon** [comment]
What the hell, this bug came back with Plasma 6 release !
